
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8765

spring:
  application:
    name: service-feign

feign.hystrix.enabled: true  #yml\u8FD8\u80FD\u8FD9\u4E48\u5E72\uFF1F\u7EDD\u4E86\uFF01
