eureka:
  client:
    serviceUrl:
      defaultZone: http://root:booszy@39.108.10.105:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

server:
  port: 8090

spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: booszy
  application:
    name: service-zuul

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000
