eureka:
  client:
    serviceUrl:
      defaultZone: http://root:booszy@39.108.10.105:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

server:
  port: 8090

spring:
  security:
    basic:
      enabled: true
    user:
      name: root
      password: booszy
  application:
    name: service-zuul

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# URL pattern
# 使用路径方式匹配路由规则。
# 参数key结构： zuul.routes.customName.path=xxx
# 用于配置路径匹配规则。
# 其中customName自定义。通常使用要调用的服务名称，方便后期管理
# 可使用的通配符有： * ** ?
# ? 单个字符
# * 任意多个字符，不包含多级路径
# ** 任意多个字符，包含多级路径
#  zuul.routes.eureka-application-service.path=/api/**
  # 参数key结构： zuul.routes.customName.url=xxx
  # url用于配置符合path的请求路径路由到的服务地址。
#  zuul.routes.eureka-application-service.url=http://127.0.0.1:8080/

zuul:
  routes:
    service-hi:
      path: /service-hi/**
      url: http://39.108.10.105:8763/
    service-data:
      path: /service-data/**
      url: http://116.62.37.59:8708/

  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000



