eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

server:
  port: 4534

spring:
  application:
    name: service-zuul

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
